name: Floop
description: "habit tracker"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flex_color_scheme: ^7.3.1
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  permission_handler: ^11.3.1
  intl: ^0.18.1
  path_provider: ^2.1.2
  flutter_heatmap_calendar: ^1.0.3
  flex_color_picker: ^3.3.0
# using this vvv library to find specific android version
  device_info_plus: ^10.1.0
  fl_chart: ^0.66.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


